name: tytil_realty
description: "Real Estate App"
publish_to: 'none'
# Flutter Version: 3.22.1
# Dart Version: 3.4.1
version: 1.0.5+5

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  pinput: ^4.0.0
  google_maps_flutter: ^2.2.8
  visibility_detector: ^0.4.0+2
  dotted_border: ^2.1.0
  flutter_rating_bar: ^4.0.1
  get_storage: ^2.1.1
  image_picker: ^1.1.2
  share_plus: ^9.0.0
  url_launcher: ^6.3.0
  connectivity_plus: ^6.1.3
  http: ^1.3.0
  font_awesome_flutter: ^10.8.0
  geocoding: ^3.0.0
  intl: ^0.20.2
  flutter_typeahead: ^5.2.0
  file_picker: ^8.0.7
  string_similarity: ^2.1.1
  flutter_widget_from_html: ^0.16.0
  html_unescape: ^2.0.0
  pin_code_fields: ^8.0.1
  dropdown_button2: ^2.3.9
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.2
  collection: ^1.18.0
  dropdown_search: ^6.0.2
  crypto: ^3.0.6
  flutter_spinkit: ^5.2.1
  app_links: ^6.4.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_gen: ^5.4.0
  flutter_gen_runner: ^5.4.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/flags/
    - assets/icons/
    - assets/myImg/
    - assets/markers/

  fonts:
    - family: Inter-Regular
      fonts:
        - asset: fonts/Inter-Regular.ttf
    - family: Inter-Medium
      fonts:
        - asset: fonts/Inter-Medium.ttf
    - family: Inter-SemiBold
      fonts:
        - asset: fonts/Inter-SemiBold.ttf
    - family: Inter-Bold
      fonts:
        - asset: fonts/Inter-Bold.ttf
